#ifndef CONSTANTS_HH
#define CONSTANTS_HH

#define MAP_SPRTE_SIZE 1920
#define MAP_COORD_SIZE 1000
#define MAP_COORD_RADIUS MAP_COORD_SIZE / 2

#define SPRTE_TO_COORD(a) ((float)(a) / (float)(MAP_SPRTE_SIZE) * (MAP_COORD_SIZE) - (MAP_COORD_RADIUS))

#define MAP_COORD_HOR_MIN -250
#define MAP_COORD_HOR_MAX 250

#define MAP_SPRTE_VER_MIN 400
#define MAP_SPRTE_VER_MAX 1400
#define MAP_COORD_VER_MIN SPRTE_TO_COORD(MAP_SPRTE_VER_MIN)
#define MAP_COORD_VER_MAX SPRTE_TO_COORD(MAP_SPRTE_VER_MAX)

#define BOMBHOUSE_SPRTE_HOR_MIN 715
#define BOMBHOUSE_SPRTE_HOR_MAX 1200
#define BOMBHOUSE_COORD_HOR_MIN SPRTE_TO_COORD(BOMBHOUSE_SPRTE_HOR_MIN)
#define BOMBHOUSE_COORD_HOR_MAX SPRTE_TO_COORD(BOMBHOUSE_SPRTE_HOR_MAX)
#define BOMBHOUSE_SPRTE_VER_SIZE 350
#define BOMBHOUSE_SPRTE_BOT_VER_POS MAP_SPRTE_SIZE - BOMBHOUSE_SPRTE_VER_SIZE
#define BOMBHOUSE_SPRTE_TOP_VER_POS BOMBHOUSE_SPRTE_VER_SIZE
#define BOMBHOUSE_COORD_BOT_VER_POS SPRTE_TO_COORD(BOMBHOUSE_SPRTE_BOT_VER_POS)
#define BOMBHOUSE_COORD_TOP_VER_POS SPRTE_TO_COORD(BOMBHOUSE_SPRTE_TOP_VER_POS)

enum BombType
{
	BOMB_BLACK,
	BOMB_RED,
	BOMB_BLUE,
	BOMB_GREEN,
};

#define BOMB_SPRITE_SIZE 256
#define BOMB_SPRITE_HITBOX_SIZE 100

#define BOMB_POSITION_RANDOM_MOVEMENT_LIMIT_MIN { MAP_COORD_HOR_MIN, MAP_COORD_VER_MIN }
#define BOMB_POSITION_RANDOM_MOVEMENT_LIMIT_MAX { MAP_COORD_HOR_MAX, MAP_COORD_VER_MAX }

#define BOMB_ANIM_INDEX_WALK_BOT_LEFT 0
#define BOMB_ANIM_INDEX_WALK_BOT_RIGHT 1
#define BOMB_ANIM_INDEX_WALK_TOP_RIGHT 2
#define BOMB_ANIM_INDEX_WALK_TOP_LEFT 3
#define BOMB_ANIM_INDEX_GRABBED 4

#endif