#ifndef CONSTANTS_HH
#define CONSTANTS_HH

#define ASSETS_PATH "Assets/"
#define ASSET_SPRITES_PATH "Sprites/"
#define ASSET_SPRITE_MAP_BG "Spr_Map_BG.png"
#define ASSET_SPRITE_MAP_MG "Spr_Map_MG.png"
#define ASSET_SPRITE_MAP_FG "Spr_Map_FG.png"
#define ASSET_SPRITE_BOMB_BODY "Spr_Bomb_Body.png"
#define ASSET_SPRITE_BOMB_DECO "Spr_Bomb_Deco.png"
#define ASSET_SPRITE_BOMBHOUSE "Spr_BombHouse.png"
#define ASSET_SPRITE_BOMBHOUSE_SCREEN "Spr_BombHouse_Screen.png"
#define ASSET_SPRITE_EXPLOSION "Spr_Explosion.png"
#define ASSET_SPRITE_GAMEOVER_OVERLAY "Spr_GameOver_Overlay.png"

#define MAP_SPRTE_SIZE 1024
#define MAP_COORD_SIZE 1000
#define MAP_COORD_RADIUS MAP_COORD_SIZE / 2

#define SPRTE_TO_COORD(a) ((float)(a) / (float)(MAP_SPRTE_SIZE) * (MAP_COORD_SIZE) - (MAP_COORD_RADIUS))

#define MAP_COORD_HOR_MIN -250
#define MAP_COORD_HOR_MAX 250

#define MAP_SPRTE_VER_MIN 200
#define MAP_SPRTE_VER_MAX 720
#define MAP_COORD_VER_MIN SPRTE_TO_COORD(MAP_SPRTE_VER_MIN)
#define MAP_COORD_VER_MAX SPRTE_TO_COORD(MAP_SPRTE_VER_MAX)

#define ROUND_BOMB_SPAWN_TIME_START 3
#define ROUND_BOMB_SPAWN_TIME_INCREMENT 0.125f
#define ROUND_BOMB_SPAWN_TIME_MIN .75f
#define ROUND_MAX_BOMBS_START 2
#define ROUND_MAX_BOMBS_INCREMENT 0.1f
#define ROUND_BOMB_HOUSE_CHANGE_TIME_START 30.f
#define ROUND_BOMB_HOUSE_CHANGE_TIME_INCREMENT 4.f
#define ROUND_BOMB_HOUSE_CHANGE_TIME_MIN 10.f
#define ROUND_BLUE_BOMB_SPAWN_TIME_START 50.f
#define ROUND_GREEN_BOMB_SPAWN_TIME_START 120.f

#define DEBUG_BOMBHOUSE_TYPE_DRAW false

#define BOMBHOUSE_LENIENCE_TIME 8.0f

#define BOMBHOUSE_ANIMATION_FRAMES 11
#define BOMBHOUSE_ANIMATION_SPEED 20

#define BOMBHOUSE_SPRTE_HOR_MIN 453
#define BOMBHOUSE_SPRTE_HOR_MAX 571
#define BOMBHOUSE_SPRITE_SIZE 256
#define BOMBHOUSE_COORD_HOR_MIN SPRTE_TO_COORD(BOMBHOUSE_SPRTE_HOR_MIN)
#define BOMBHOUSE_COORD_HOR_MAX SPRTE_TO_COORD(BOMBHOUSE_SPRTE_HOR_MAX)
#define BOMBHOUSE_SPRTE_BOT_VER_POS MAP_SPRTE_SIZE - 240
#define BOMBHOUSE_SPRTE_TOP_VER_POS 186
#define BOMBHOUSE_COORD_BOT_VER_POS SPRTE_TO_COORD(BOMBHOUSE_SPRTE_BOT_VER_POS)
#define BOMBHOUSE_COORD_TOP_VER_POS SPRTE_TO_COORD(BOMBHOUSE_SPRTE_TOP_VER_POS)
#define BOMBHOUSE_SCREEN_SPRITE_SIZE 128
#define BOMBHOUSE_SCREEN_COORD_SIZE 122
#define BOMBHOUSE_SCREEN_TOP_SPRTE_X 678
#define BOMBHOUSE_SCREEN_TOP_SPRTE_Y 85
#define BOMBHOUSE_SCREEN_TOP_COORD_X SPRTE_TO_COORD(BOMBHOUSE_SCREEN_TOP_SPRTE_X)
#define BOMBHOUSE_SCREEN_TOP_COORD_Y SPRTE_TO_COORD(BOMBHOUSE_SCREEN_TOP_SPRTE_Y)
#define BOMBHOUSE_SCREEN_BOT_SPRTE_X 347
#define BOMBHOUSE_SCREEN_BOT_SPRTE_Y 907
#define BOMBHOUSE_SCREEN_BOT_COORD_X SPRTE_TO_COORD(BOMBHOUSE_SCREEN_BOT_SPRTE_X)
#define BOMBHOUSE_SCREEN_BOT_COORD_Y SPRTE_TO_COORD(BOMBHOUSE_SCREEN_BOT_SPRTE_Y)

#define BOMB_TYPE_COUNT 5
enum BombType { BOMB_BLACK, BOMB_RED, BOMB_BLUE, BOMB_GREEN, BOMB_ABOUT_TO_EXPLODE, BOMB_INVALID };

#define BOMB_CHANCE_TO_SPAWN_RANDOM_COLOR 10

#define DEBUG_BOMB_HITBOX_DRAW false

#define BOMB_EXPLODE_TIME 45.0f

#define BOMB_SPRITE_SIZE 256
#define BOMB_SPRITE_HITBOX_SIZE 100

#define BOMB_POSITION_RANDOM_MOVEMENT_LIMIT_MIN { MAP_COORD_HOR_MIN, MAP_COORD_VER_MIN }
#define BOMB_POSITION_RANDOM_MOVEMENT_LIMIT_MAX { MAP_COORD_HOR_MAX, MAP_COORD_VER_MAX }

#define BOMB_RELEASED_TOP 1
#define BOMB_RELEASED_BOT 2
#define BOMB_RELEASED_DEF 3

#define BOMB_PLACED_TOP 0
#define BOMB_PLACED_BOT 1

#define BOMB_SPAWN_POS_X_LEFT -500
#define BOMB_SPAWN_POS_X_RIGHT 500

#define BOMB_ANIM_INDEX_WALK_BOT_LEFT 0
#define BOMB_ANIM_INDEX_WALK_BOT_RIGHT 1
#define BOMB_ANIM_INDEX_WALK_TOP_RIGHT 2
#define BOMB_ANIM_INDEX_WALK_TOP_LEFT 3
#define BOMB_ANIM_INDEX_GRABBED 4
#define BOMB_ANIM_INDEX_PLACED_BOT 5
#define BOMB_ANIM_INDEX_PLACED_TOP 6

#define BOMB_GRAB_MOUSE_SCALE_INDEX 2.f
#define BOMB_GRAB_MOUSE_HITBOX_OFFSET_Y 10
#define BOMB_GRABBED_SCALE_INDEX 1.25f

#define EXPLOSION_SPRITE_SIZE 64
#define EXPLOSION_ANIMATION_SPRITES 16
#define EXPLOSION_SIZE 160
#define EXPLOSION_DURATION 1.0f

#define GAMEOVER_CUTSCENE_TIME 3.0f
#define GAMEOVER_OVERLAY_SPRTE_SIZE 1024
#define GAMEOVER_OVERLAY_SPRTE_COLOR {255,255,255,200}

#define GAMEOVER_OVERLAY_CUTSCENE_TIME 3.5f
#define GAMEOVER_OVERLAY_CUTSCENE_FADEIN_TIME 0.25f
#define GAMEOVER_OVERLAY_CUTSCENE_SIZE_START 37500
#define GAMEOVER_OVERLAY_CUTSCENE_SIZE_END 2222
#define GAMEOVER_OVERLAY_CUTSCENE_OSCILATE_TIME 2.75f
#define GAMEOVER_OVERLAY_CUTSCENE_OSCILATE_SCALE 70.f
#define GAMEOVER_OVERLAY_CUTSCENE_OSCILATE_VELOCITY 5.f

#endif